import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Inter } from 'next/font/google'
import "./globals.css";
import ReactQuery from "@/lib/providers/tanstackQuerry.provider";
import NavbarSwitcher from "@/components/common/navbar/NavbarSwitcher";
import ToastProvider from "@/lib/providers/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ['latin'] })



export const metadata: Metadata = {
  title: "Laridae Premium Tea",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${inter.className} antialiased`}
      >
        <main>
          <ReactQuery>
            <ToastProvider/>
            <NavbarSwitcher/>
              {children}
          </ReactQuery>
    
        </main>

      </body>
    </html>
  );
}
